### ISSUE TITLE
"/pe random" Not Functioning

### ISSUE THREAD

**Issue by ghost** [Ravendwyr/PetEmote#1]
Hello there! I've been using PetEmote later, and found today that if I do `/pe random` nothing happens for my pet. My pet is an Alpaca (labeled Camel in-game).

The reason I mention the type of pet is because my Saurolisk (lizard) seems to be the only pet I have that randomly emotes on his own.

I have set up my alpaca with her gender and family type, but alas, it's still not working.

**Comment by Ravendwyr** [comment]
Hello there.

I have a sneaky suspicion your installed version is out of date ~~which is totally my fault~~. The emote database was updated some time ago but was never properly flagged as a release package. I have now done so and Version 1.8.15 should be available for download from CurseForge and WoWInterface shortly.

Please give this new version a try and see if that does the trick.

Cheers!

**Comment by ghost** [comment]
Thanks Ravendwyr! I'll go ahead and update it when I see the version change out, and let you know if I have any trouble. Thanks for jumping on that so quickly--it's much appreciated. Great, fun addon! :)

**Comment by Ravendwyr** [comment]
It's been two months and I haven't heard otherwise so I'm going to close this as fixed. Let me know if anything else crops up.
